name: CI/CD

on:
  push:
    branches:
      - main  # или ветка, на которую хотите настраивать пуш
  pull_request:
    branches:
      - main  # или ветка, на которую хотите настраивать PR

jobs:
  build:
    runs-on: ubuntu-latest  # или другой тип ОС (например, windows-latest)

    steps:
      # Checkout репозитория
      - name: Checkout code
        uses: actions/checkout@v2

      # Установка JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'  # или 'zulu', в зависимости от вашего JDK

      # Синхронизация зависимостей
      - name: Sync dependencies
        run: ./gradlew build --no-daemon

      # Проверка и сборка проекта
      - name: Build project
        run: ./gradlew build --no-daemon

      # Запуск тестов
      - name: Run tests
        run: ./gradlew test --no-daemon

      # Пушить изменения в репозиторий (если все прошло успешно)
      - name: Push changes
        if: success()
        run: git push origin main
